- name: Setup Smile Website Server
  hosts: smile_server
  become: yes  # Run as root

  tasks:
    # Install Docker, Git, and Nginx
    - name: Install Docker, Git, and Nginx
      apt:
        name:
          - docker.io
          - git
          - nginx
        state: present
        update_cache: yes

    # Ensure Docker is running
    - name: Start and Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    # Stop and Disable Nginx
    - name: Stop and Disable Nginx
      service:
        name: nginx
        state: stopped
        enabled: no

    # Clone Smile Website Code from GitHub
    - name: Clone Smile Website Repository
      git:
        repo: "https://github.com/santhoshcy/smile.git"
        dest: /var/www/smile
        version: main

    # Build Docker Image
    - name: Build Docker Image
      command: docker build -t smile-website /var/www/smile/

    # Remove Existing Container (if any)
    - name: Remove Existing Smile Website Container
      command: docker rm -f smile-container
      ignore_errors: yes

    # Run Smile Website in a Docker Container
    - name: Run Smile Website Container
      docker_container:
        name: smile-container
        image: smile-website
        state: started
        recreate: yes
        published_ports:
          - "80:80"
        restart_policy: always
